name: 构建 WebDriverAgent

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # macos-latest 可能即将迁移，建议固定版本

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo gem install cocoapods
          pod install

      - name: 构建未签名IPA
        run: |
          xcodebuild -workspace WebDriverAgent.xcworkspace \
                     -scheme WebDriverAgentRunner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/WebDriverAgent.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/WebDriverAgent.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD/build

      - name: 查看输出文件
        run: ls -al build

      - name: 上传未签名IPA
        uses: actions/upload-artifact@v4
        with:
          name: ulink-agent-unsigned.ipa
          path: build/*.ipa
