name: Build unsigned WebDriverAgentRunner IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: wzhr000/WebDriverAgent
        fetch-depth: 1

    - name: Install Carthage
      run: brew install carthage

    - name: Bootstrap dependencies
      run: ./Scripts/bootstrap.sh -d

    - name: Clean previous build
      run: xcodebuild clean -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner

    - name: Archive WebDriverAgentRunner (no signing)
      run: |
        xcodebuild archive \
          -project WebDriverAgent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -destination 'generic/platform=iOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -archivePath ${{ github.workspace }}/build/WebDriverAgentRunner.xcarchive

    - name: Create ExportOptions.plist
      run: |
        cat > ExportOptions.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>development</string>
          <key>signingStyle</key>
          <string>none</string>
          <key>compileBitcode</key>
          <false/>
          <key>stripSwiftSymbols</key>
          <true/>
        </dict>
        </plist>
        EOF

    - name: Export unsigned IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath ${{ github.workspace }}/build/WebDriverAgentRunner.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath ${{ github.workspace }}/build/Unsigned

    - name: Upload unsigned IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: WebDriverAgentRunner-unsigned-ipa
        path: build/Unsigned/WebDriverAgentRunner.ipa
