- name: Build .app with xcodebuild
  run: |
    xcodebuild -workspace WebDriverAgent.xcworkspace \
               -scheme WebDriverAgentRunner \
               -sdk iphoneos \
               -configuration Release \
               -derivedDataPath build

- name: Package .ipa manually
  run: |
    mkdir -p Payload
    cp -r build/Build/Products/Release-iphoneos/WebDriverAgentRunner-Runner.app Payload/
    zip -r WebDriverAgentRunner.ipa Payload
    mkdir -p output
    mv WebDriverAgentRunner.ipa output/
    rm -rf Payload

- name: Upload IPA
  uses: actions/upload-artifact@v4
  with:
    name: WebDriverAgentRunner.ipa
    path: output/WebDriverAgentRunner.ipa
